language: node_js
node_js:
  - 10 # active LTS
  - 12 # current

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
  fast_finish: true

cache: npm

global:
  secure: Y4eP+Mf66AJOm5Fq8vSRxKFn+jPtkCRC7A0x1VTXqch/pkF7lbQsaFa3oFZcQMWJ8EWJQ+7jsZrKqE5H5g9cSsrTATa29n3vCU2Yw8gboX3V7e6ubX89qcJX3xbXTB6pSFoWJaUa63Lmw99FAZcwzvDKJ4OVVU+ewELxg5n3wLp1bL/9+m0ZKJJ8clNqGh+sUIhhgjJBN9FLTPegPoCS+zaTPq/smoIdj52nP4SI9k+iOUyX3CRVxROUxMD7IEKuGraDpnb1kh589hmGGm1nAlH1SENTowkXCklPdQC14YoEjenwFTHuB1kp/W6Qnk6GNe8JQ46ByhaBZsf1rIO1FP1bNO7vxPOIMwbyNDLCA+gk8JspESaYs6m8qGavDjYeS8FkzjyOeU5U2CnEPYfuX/fB86u5sGd3G277KMFW0A5JMzQZ23Dhm93qWdZ6kVKDTGngqcyywMa+Bgdrz2YetULSKzCeLidYO5lxk4MGmpwuuGxjVY55/vuqLuMX20ZHibQyxb7qSx41LFZxq5GhtcBISje7FdPLZ7fxQqWIY5k2qpaxzVAKgAU9T3VY1rEEQc7Vv68g1C/V3jiDnjeXG1cKEq0VUsLtJM0gCG0vWvietfad++Lhr1SeFlSBusFqmQODnR86qRIESriNH3e4PsxFIKFP5gSDoyUDYYw2CVU=

script:
  - npm install
  - make

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_ACCESS_KEY
    local_dir: dist
    bucket: black-highlighter-dist
    on:
      os: linux
      node_js: 12
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    local_dir: dist
    keep_history: true
    deployment_file: true
    verbose: true
    on:
      os: linux
      node_js: 12
      branch: master

notifications:
  - email:
    recipients:
      - ammon.i.smith@gmail.com
      - gophilm@gmail.com
      - rossjrw@gmail.com
    on_success: change
    on_failure: always
